version: '3.8'

services:
  dntl.api:
    image: SchoolApp.api
    build:
      context: .
      dockerfile: SchoolApp.Api/Dockerfile
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: DNTLMongoDb*123
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
    driver: local